### PR TITLE
feat: package scaffolding with moonrepo

### PR DESCRIPTION
**Pull request by kylemcd**
### Description
- Adds the ability to scaffold a new project via cli command `yarn generate:package`
- Uses [moonrepo](https://moonrepo.dev/docs/guides/codegen#generating-code-from-a-template) for code generation
- Adds `package` template

### Tasks
[KNO-6151](https://linear.app/knock/issue/KNO-6151/[telegraph]-add-scaffolding-commands-for-packages)

### CODE REVIEW

**Comment by kylemcd** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/knocklabs/telegraph/108?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#108** <a href="https://app.graphite.dev/github/pr/knocklabs/telegraph/108?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#107** <a href="https://app.graphite.dev/github/pr/knocklabs/telegraph/107?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kylemcd and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by connorlindsey — APPROVED** [review]
Tested and this is super nice! Would be cool to see if there's anything else we can generate/automate, but atm I don't think there are a ton of other things required to bootstrap a new package (like adding the css to the Storybook global.css)

**Comment by kylemcd** [comment]
> Tested and this is super nice! Would be cool to see if there's anything else we can generate/automate, but atm I don't think there are a ton of other things required to bootstrap a new package (like adding the css to the Storybook global.css)

Ah yeah, that would be cool to be able to append that.

**Comment by kylemcd** [comment]
### Merge activity

* **Jun 6, 4:50 PM CDT**: @kylemcd started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/knocklabs/telegraph/108).

**Pull request merged**
